spring.application.name=fulfillment-match

spring.datasource.url=jdbc:postgresql://localhost:5432/fulfillment_match
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true